# Generated by Django 5.2 on 2025-04-15 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='order',
            field=models.IntegerField(),
        ),
    ]
