# Generated by Django 5.2 on 2025-04-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0005_remove_room_itinerary'),
        ('itineraries', '0003_itinerary_created_at_itinerary_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='djangochat.room'),
        ),
    ]
