# Generated by Django 5.2 on 2025-04-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0003_room_owner_roommembership_room_participants'),
        ('itineraries', '0003_itinerary_created_at_itinerary_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='itinerary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='itineraries.itinerary'),
        ),
    ]
