# Generated by Django 5.2 on 2025-04-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0004_room_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='itinerary',
        ),
    ]
